version: "3"

services:
  minio:
    build: .
    volumes:
      - ./minio/data:/data
      - ./minio/config:/root/.minio
    ports:
      - "${MINIO_PORT}:9000"
      - "${MINIO_CONSOLE_PORT}:9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    networks:
      - frontend
      - backend

networks:
  frontend:
  backend:

volumes:
  minio:
